name: quran_quest
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev



version: 1.0.0+1

environment:
  sdk: ^3.6.1



dependencies:
  flutter:
    sdk: flutter


  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
# ! Using state management.
  flutter_bloc: ^9.0.0
  bloc: ^9.0.0
# ! Being able to compare objects in Dart.
  equatable: ^2.0.7
# ! Using handle this http request
  dio: ^5.8.0+1
# ! Using Beautiful and understandable (log Message ).
  logger: ^2.5.0
# ! Using all screen Size Responsive.
  flutter_screenutil: ^5.9.3
# ! Using handle this functional programming
  fpdart: ^1.1.1
# ! Using handle this text size.
  auto_size_text: ^3.0.0
# ! Service Locator
  get_it: ^8.0.3
# ! Using SVG images in Flutter
  flutter_svg: ^2.0.17
# ! Using new Icon 
  iconsax: ^0.0.8
# ! Using Localization multiple languages
  easy_localization: ^3.0.7+1
# !This is a Flutter package for a Tinder-like card swiper.✨
  flutter_card_swiper: ^7.0.2
# ! Added dependencies: freezed_annotation for immutable models and json_annotation for JSON serialization.
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  flutter_staggered_grid_view: ^0.7.0
  popover: 
  
  
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 
  pretty_dio_logger: ^1.4.0
  easy_localization_generator: ^0.3.3 

  build_runner: ^2.4.15
#! Added freezed for immutable data classes and json_serializable for JSON serialization.
  freezed: ^3.0.0-0.0.dev
  json_serializable: 6.9.0
  
  very_good_analysis: ^7.0.0
  
  


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  #! To add assets to your application, add an assets section, like this:
  assets:
    - assets/quran_icon/
    - assets/images/
    - assets/svg_images/
    - assets/translations/



  #! example: Fonts in the application

  fonts:
    - family: AmiriQuran
      fonts:
        - asset: assets/fonts/AmiriQuran-Regular.ttf
    - family: MeQuran
      fonts:
        - asset: assets/fonts/me_quran Regular.ttf
    - family: NotoNastaliqUrdu
      fonts:
        - asset: assets/fonts/NotoNastaliqUrdu-VariableFont_wght.ttf


  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
