#!/usr/bin/env bash

# ⚡ QUICK START - Quran Quest Release in 5 Minutes
# یہ سب سے آسان اور تیز طریقہ ہے

echo "╔═══════════════════════════════════════════════════╗"
echo "║  🚀 Quran Quest - 5 Minute Release Guide          ║"
echo "╚═══════════════════════════════════════════════════╝"
echo ""

echo "📋 OPTION 1: Manual Release (NO Setup Required)"
echo "─────────────────────────────────────────────"
echo ""
echo "# Step 1: Build APK"
echo "flutter build apk --release"
echo ""
echo "# Step 2: Get APK"
echo "ls -lh build/app/outputs/flutter-apk/app-release.apk"
echo ""
echo "# Step 3: Go to GitHub"
echo "open https://github.com/Muhammadjj/Quran-Quest-/releases"
echo ""
echo "# Step 4: Create Release Manually"
echo "- Click 'Create a new release'"
echo "- Tag: v1.0.0"
echo "- Title: Quran Quest v1.0.0"
echo "- Drag APK file"
echo "- Click 'Publish'"
echo ""
echo "✅ Done! Time: ~15 minutes (includes build time)"
echo ""

echo ""
echo "🤖 OPTION 2: Automated Release (RECOMMENDED)"
echo "─────────────────────────────────────────────"
echo ""
echo "First time setup (ONE TIME ONLY):"
echo ""
echo "# 1. Generate Keystore"
echo "keytool -genkey -v -keystore android/app/upload-keystore.jks \\"
echo "    -keyalg RSA -keysize 4096 -validity 10000 -alias upload"
echo ""
echo "# 2. Add GitHub Secrets"
echo "# URL: https://github.com/Muhammadjj/Quran-Quest-/settings/secrets/actions"
echo ""
echo "# Secret 1: KEYSTORE_FILE"
echo "base64 -w 0 android/app/upload-keystore.jks"
echo ""
echo "# Secret 2-4: Add passwords and alias"
echo ""
echo "# 3. Update .gitignore"
echo "git add .gitignore && git commit -m 'Add security'"
echo ""
echo "Then, for every release:"
echo ""
echo "# Just create a tag!"
echo "git tag v1.0.0"
echo "git push origin v1.0.0"
echo ""
echo "✅ GitHub Actions builds and releases automatically!"
echo "⏱️  Time to release: 1 minute (after 10 min build time)"
echo ""

echo ""
echo "📚 DOCUMENTATION"
echo "─────────────────────────────────────────────"
echo ""
echo "Quick references:"
echo "  1. RELEASE_GUIDE.md ..................... Main guide"
echo "  2. SIGNING.md ........................... Android signing"
echo "  3. ADVANCED_RELEASE_TIPS.md ............ Pro tips"
echo "  4. SETUP_GITHUB_SECRETS.sh ............ Step-by-step setup"
echo ""

echo ""
echo "🔍 FILE LOCATIONS"
echo "─────────────────────────────────────────────"
echo ""
echo "Release scripts:"
echo "  ./release.sh ........................... Main release script"
echo "  ./pre-release-check.sh ................ Validation checks"
echo "  .github/workflows/release-apk.yml .... GitHub Actions workflow"
echo ""
echo "Generated APK:"
echo "  build/app/outputs/flutter-apk/app-release.apk"
echo ""
echo "GitHub Release page:"
echo "  https://github.com/Muhammadjj/Quran-Quest-/releases"
echo ""

echo ""
echo "⚡ SUPER QUICK - Copy & Paste Ready"
echo "─────────────────────────────────────────────"
echo ""

cat << 'QUICKCOPY'
# MANUAL RELEASE
flutter build apk --release && gh release create v1.0.0 build/app/outputs/flutter-apk/app-release.apk --title "Quran Quest v1.0.0" --notes "New release"

# AUTOMATED (after first-time setup)
git tag v1.0.0 && git push origin v1.0.0
QUICKCOPY

echo ""
echo "═══════════════════════════════════════════════════"
echo ""
echo "❓ Need help?"
echo ""
echo "  Issue with build?"
echo "  $ flutter clean && flutter pub get && flutter build apk --release -v"
echo ""
echo "  Workflow not working?"
echo "  Check: https://github.com/Muhammadjj/Quran-Quest-/actions"
echo ""
echo "  Secrets not configured?"
echo "  Run: ./SETUP_GITHUB_SECRETS.sh"
echo ""
echo "  Can't find APK?"
echo "  $ find build -name '*.apk' -type f"
echo ""

echo "═══════════════════════════════════════════════════"
echo ""
