class ParahListUtils {
  static final List<Map<String, dynamic>> juzNames = [
    {
      'number': 1,
      'arabic': 'آلم',
      'english': 'Alif Laam Meem',
      'total_verses': 148,
    },
    {
      'number': 2,
      'arabic': 'سَيَقُولُ',
      'english': 'Sayaqool',
      'total_verses': 111,
    },
    {
      'number': 3,
      'arabic': 'تِلْكَ ٱلرُّسُلُ',
      'english': 'Tilkar rusul',
      'total_verses': 126,
    },
    {
      'number': 4,
      'arabic': 'لَنْ تَنَالُو',
      'english': 'Lann Tanaloo',
      'total_verses': 131,
    },
    {
      'number': 5,
      'arabic': 'وَٱلْمُحْصَنَاتُ',
      'english': 'Wal Mohsinaat',
      'total_verses': 124,
    },
    {
      'number': 6,
      'arabic': 'لَا يُحِبُّ ٱللهُ',
      'english': 'La yuhibbullaho',
      'total_verses': 110,
    },
    {
      'number': 7,
      'arabic': 'وَإِذَا سَمِعُوا',
      'english': 'Wa Iza Samay_oo',
      'total_verses': 149,
    },
    {
      'number': 8,
      'arabic': 'وَلَوْ أَنَّنَا',
      'english': 'Walao Annana',
      'total_verses': 142,
    },
    {
      'number': 9,
      'arabic': 'قَالَ ٱلْمَلَأُ',
      'english': 'Qaalal Malao',
      'total_verses': 159,
    },
    {
      'number': 10,
      'arabic': 'وَٱعْلَمُواْ',
      'english': 'Waalamoo',
      'total_verses': 127,
    },
    {
      'number': 11,
      'arabic': 'يَعْتَذِرُونَ',
      'english': 'Yaataziroon',
      'total_verses': 151,
    },
    {
      'number': 12,
      'arabic': 'وَمَا مِنْ دَآبَّةٍ',
      'english': 'Wama min Daabbatin',
      'total_verses': 170,
    },
    {
      'number': 13,
      'arabic': 'وَمَا أُبَرِّئُ',
      'english': 'Wama ubarriyo',
      'total_verses': 154,
    },
    {
      'number': 14,
      'arabic': 'رُبَمَا',
      'english': 'Rubama',
      'total_verses': 227,
    },
    {
      'number': 15,
      'arabic': 'سُبْحَانَ ٱلَّذِى',
      'english': 'Subhanal Lazi',
      'total_verses': 185,
    },
    {
      'number': 16,
      'arabic': 'قَالَ أَلَمْ',
      'english': 'Qaal Alam',
      'total_verses': 269,
    },
    {
      'number': 17,
      'arabic': 'ٱقْتَرَبَ لِلْنَّاس',
      'english': 'Iqtaraba',
      'total_verses': 190,
    },
    {
      'number': 18,
      'arabic': 'قَدْ أَفْلَحَ',
      'english': 'Qadd Aflahaa',
      'total_verses': 202,
    },
    {
      'number': 19,
      'arabic': 'وَقَالَ ٱلَّذِينَ',
      'english': 'Wa qaalal lazina',
      'total_verses': 339,
    },
    {
      'number': 20,
      'arabic': 'أَمَّنْ خَلَقَ',
      'english': 'Ammann Khalaq',
      'total_verses': 171,
    },
    {
      'number': 21,
      'arabic': 'أُتْلُ مَاأُوْحِیَ',
      'english': 'Utloo ma oohiyaa',
      'total_verses': 178,
    },
    {
      'number': 22,
      'arabic': 'وَمَنْ يَّقْنُتْ',
      'english': 'Wamaee Yaqnut',
      'total_verses': 169,
    },
    {
      'number': 23,
      'arabic': 'وَمَآ لي',
      'english': 'Wamaali',
      'total_verses': 357,
    },
    {
      'number': 24,
      'arabic': 'فَمَنْ أَظْلَمُ',
      'english': 'Faman Azlamo',
      'total_verses': 175,
    },
    {
      'number': 25,
      'arabic': 'إِلَيْهِ يُرَدُّ',
      'english': 'IIaeyhi yuraddo',
      'total_verses': 246,
    },
    {'number': 26, 'arabic': 'حم', 'english': 'Haa Meem', 'total_verses': 195},
    {
      'number': 27,
      'arabic': 'قَالَ فَمَا خَطْبُكُم',
      'english': 'Qaala Fama Khatbokum',
      'total_verses': 399,
    },
    {
      'number': 28,
      'arabic': 'قَدْ سَمِعَ ٱللهُ',
      'english': 'Qadd Samiullah',
      'total_verses': 137,
    },
    {
      'number': 29,
      'arabic': 'تَبَارَكَ ٱلَّذِى',
      'english': 'Tabarakal Lazi',
      'total_verses': 431,
    },
    {
      'number': 30,
      'arabic': 'عَمَّ',
      'english': 'Amma',
      'total_verses': 564,
    },
  ];

  // static const juzNames = [
  //   'آلم',
  //   'سَيَقُولُ',
  //   'تِلْكَ ٱلْرُّسُلُ',
  //   'لَنْ تَنَالُو',
  //   'وَٱلْمُحْصَنَاتُ',
  //   'لَا يُحِبُّ ٱللهُ',
  //   'وَإِذَا سَمِعُوا',
  //   'وَلَوْ أَنَّنَا',
  //   'قَالَ ٱلْمَلَأُ',
  //   'وَٱعْلَمُواْ',
  //   'يَعْتَذِرُونَ',
  //   'وَمَا مِنْ دَآبَّةٍ',
  //   'وَمَا أُبَرِّئُ',
  //   'رُبَمَا',
  //   'سُبْحَانَ ٱلَّذِى',
  //   'قَالَ أَلَمْ',
  //   'ٱقْتَرَبَ لِلْنَّاس',
  //   'قَدْ أَفْلَحَ',
  //   'وَقَالَ ٱلَّذِينَ',
  //   'أَمَّنْ خَلَقَ',
  //   'أُتْلُ مَاأُوْحِیَ',
  //   'وَمَنْ يَّقْنُتْ',
  //   'وَمَآ لي',
  //   'فَمَنْ أَظْلَمُ',
  //   'إِلَيْهِ يُرَدُّ',
  //   'حم',
  //   'قَالَ فَمَا خَطْبُكُم',
  //   'قَدْ سَمِعَ ٱللهُ',
  //   'تَبَارَكَ ٱلَّذِى',
  //   'عَمَّ',
  // ];
}
