import 'dart:developer';
import 'dart:io';
import 'dart:math' as math;

import 'package:flutter/foundation.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_card_swiper/flutter_card_swiper.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:flutter_svg/svg.dart';
import 'package:iconsax/iconsax.dart';
import 'package:photo_view/photo_view.dart';
import 'package:quran_quest/core/manager/managers.dart';
import 'package:quran_quest/export/export.dart';
import 'package:quran_quest/feature/Quran_Qibla_Direction/presentation/view/quran_qibla_direction.dart';
import 'package:quran_quest/feature/Quran_Quest_DashBoard/data/model/Quran_Flash_Card/quran_flash_cards_model.dart';
import 'package:quran_quest/feature/Quran_Quest_DashBoard/data/model/random_card_surah_model.dart';
import 'package:quran_quest/feature/Quran_Quest_DashBoard/domain/entities/quran_allah_name_model.dart';
import 'package:quran_quest/feature/Quran_Quest_DashBoard/presentation/bloc/random_ayah_bloc.dart';
import 'package:share_plus/share_plus.dart';

part 'Allah_Name_Card_Swiper_Widget/allah_name_swiper_widget.dart';
part 'Dashboard_Widgets/Dashboard_Drawer/dashboard_drawer.dart';
part 'Dashboard_Widgets/Dashboard_Drawer/dashboard_drawer_footer_widget.dart';
part 'Dashboard_Widgets/Dashboard_Drawer/dashboard_drawer_header_widget.dart';
part 'Dashboard_Widgets/Dashboard_Drawer/dashboard_drawer_items.dart';
part 'Dashboard_Widgets/dashboard_verses_card_widget.dart';
part 'Dashboard_Widgets/quran_allah_name_card.dart';
part 'Landing_Page_Widgets/bottom_navigation_bar_items.dart';
part 'Landing_Page_Widgets/landing_page.dart';
part 'Landing_Page_Widgets/list_of_pages.dart';
part 'Quran_Flashes_Card/flashes_card_design.dart';
part 'Quran_Flashes_Card/flashes_card_main_screen.dart';
part 'Quran_Flashes_Card/flashes_card_main_screen_widget.dart';
part 'Quran_Flashes_Card/flashes_card_capture_image_view_widget.dart';
part 'Quran_Flashes_Card/flash_card_select_language_widget.dart';
